[project]
name = "livia"
version = "0.1.1"
description = "Livia Zaharia personal website built with Reflex"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "reflex>=0.9.1",
    "typer>=0.24.1",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project.scripts]
start = "livia.start:app"
build = "livia.start:build_app"
prod  = "livia.start:prod_app"
serve = "livia.start:serve_app"
