[project]
name = "livia"
version = "0.1.0"
description = "Livia Zaharia personal website built with Reflex"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "compas>=2.15.1",
    "pythreejs>=2.4.2",
    "pyyaml>=6.0.3",
    "reflex>=0.8.27",
    "typer>=0.15",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project.scripts]
start = "livia.start:app"
